In [1]:
import numpy as np


In [ ]:
# Creating a 1D Array
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [3]:
# creating 2d array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)


[[1 2 3]
 [4 5 6]]


In [4]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3d)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
zeros = np.zeros((2, 3))  # 2 rows, 3 columns of zeros
ones = np.ones((3, 3))    # 3x3 array of ones
full_array = np.full((2, 2), 99)  # Filled with 99
identity_matrix = np.eye(3)  # 3x3 identity matrix

print(zeros)
print(ones)
print(full_array)
print(identity_matrix)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[99 99]
 [99 99]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Generating Sequences & Random Numbers

In [8]:
# Using arange()
arr = np.arange(1, 10, 2)  # Start=1, Stop=10, Step=2
print(arr)


[1 3 5 7 9]


In [ ]:
# Using linspace()
arr = np.linspace(0, 5, 10)  # 10 values between 0 and 5
print(arr)


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [ ]:
# Random Number Generation
rand_array = np.random.rand(3, 3)  # 3x3 array with random values
rand_ints = np.random.randint(1, 10, (2, 2))  # 2x2 array of random integers (1-10) 
# np.random.rand() – Generates Random Floating-Point Numbers
# np.random.randint() – Generates Random Integers

print(rand_array)
print(rand_ints)


[[0.18263471 0.91194003 0.07791768]
 [0.23631088 0.8683767  0.79879261]
 [0.62863432 0.5339857  0.47761658]]
[[7 7]
 [4 7]]


In [ ]:
# Array Properties
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)  # (2,3) → (rows, columns)
print(arr.size)   # 6 (total elements)
print(arr.dtype)  # int32 (data type of elements)
print(arr.ndim)   # 2 (number of dimensions)


(2, 3)
6
int64
2


In [15]:
# Reshaping & Flattening Arrays
arr = np.arange(1, 10)
print(arr)
reshaped = arr.reshape(3, 3)  # Convert to 3x3 matrix
flattened = reshaped.flatten()  # Convert back to 1D

print(reshaped)
print(flattened)


[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [16]:
# indexing
arr = np.array([10, 20, 30, 40, 50])
print(arr[1])  # 20


20


In [17]:
# slicing
print(arr[1:4])  # [20, 30, 40]
print(arr[:3])   # [10, 20, 30]
print(arr[-2:])  # [40, 50]


[20 30 40]
[10 20 30]
[40 50]


In [18]:
# indexing in 2d array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[0, 1])  # Element at row=0, column=1 → 2
print(arr[:, 1])  # Second column → [2, 5]


2
[2 5]


In [19]:
# Mathematical operation
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(arr1 + arr2)  # [5 7 9]
print(arr1 - arr2)  # [-3 -3 -3]
print(arr1 * arr2)  # [4 10 18]
print(arr1 / arr2)  # [0.25 0.4 0.5]


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# Universal Functions (ufuncs)
arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))  # Square root
print(np.exp(arr))   # Exponential 
print(np.log(arr))   # Logarithm
print(np.sin(arr))   # Sine function


[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[0.         1.38629436 2.19722458 2.77258872]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]


In [21]:
# Statistic
arr = np.array([10, 20, 30, 40])

print(np.sum(arr))    
print(np.mean(arr))    
print(np.min(arr))     
print(np.max(arr))     
print(np.std(arr))     


100
25.0
10
40
11.180339887498949


In [22]:
# matrix operation
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A + B)  # Matrix addition
print(A * B)  # Element-wise multiplication
print(A @ B)  # Matrix multiplication
print(np.dot(A, B))  # Alternative for matrix multiplication
print(np.linalg.inv(A))  # Inverse of matrix A
print(np.linalg.det(A))  # Determinant of A


[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [23]:
#  Broadcasting in numpy
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10

print(arr + scalar)  # Broadcasting scalar addition


[[11 12 13]
 [14 15 16]]


In [ ]:
# saving and loading in numpy
arr = np.array([1, 2, 3, 4, 5])

np.save("data.npy", arr)  # Save as .npy file
loaded_arr = np.load("data.npy")  # Load the file
print(loaded_arr)
# it saves as non- readable format


[1 2 3 4 5]


In [ ]:
np.savetxt("data.txt", arr, fmt="%d")  # Save as text   and %d indicates it is integer (saved as integer)
loaded_txt_arr = np.loadtxt("data.txt")  # Load the text file
print(loaded_txt_arr)


[1. 2. 3. 4. 5.]
